# -*- mode: dockerfile -*-
FROM ruby:3.1.2-bullseye

RUN mkdir /app
WORKDIR /app

RUN gem install bundler -v 2.3.14

COPY Gemfile Gemfile
COPY Gemfile Gemfile.lock
RUN bundle install

COPY ./app ./app
COPY ./bin ./bin
COPY ./.bundle ./.bundle
COPY ./config ./config
COPY ./db/migrate ./db/migrate
COPY ./db/schema.rb ./db/schema.rb
COPY ./db/seeds.rb ./db/seeds.rb
COPY ./lib ./lib
COPY ./public ./public

COPY config.ru config.ru
COPY Rakefile Rakefile

RUN rails db:migrate

#CMD ["/bin/bash"]
#CMD ["rails", "server", "--binding=0.0.0.0"]
CMD ["/bin/puma"]

# Build command:
# docker build --network host . -t ror-sample-app-debug && docker run --network host --rm -p 3000 -it ror-sample-app-debug
