apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ror-sample-app-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: {{ .Values.storageClassName | quote }}
