apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: ror
  labels:
    project: ror-sample-app
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ror-sample-app
          # Don't pull always; using a local image here
          imagePullPolicy: IfNotPresent
          command: ["rails", "db:migrate"]
          env:
            - name: SAMPLE_APP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          # resources:
          #   limits:
          #     cpu: 500m
          #     memory: 512Mi
      restartPolicy: Never
