apiVersion: v1
kind: PersistentVolume
metadata:
  name: ror-sample-app-db-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /volumes/ror-sample-app-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kiamol
            operator: In
            values:
              - ch05
