apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ror-sample-app-db-pvc
  namespace: ror
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  #storageClassName: local-path
  storageClassName: do-block-storage-retain
