apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ror-sample-app-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
